"""Add booking_reference to booking_requests, password_hash to customers

Revision ID: 1dfd3c9a2560
Revises: 721dae0bf4a8
Create Date: 2026-09-08 21:09:00.433724

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1dfd3c9a2560"
down_revision = "721dae0bf4a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("booking_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("booking_reference", sa.String(length=16), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_booking_requests_booking_reference"), ["booking_reference"], unique=True
        )

    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("password_hash", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.drop_column("password_hash")

    with op.batch_alter_table("booking_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_booking_requests_booking_reference"))
        batch_op.drop_column("booking_reference")

    # ### end Alembic commands ###
