"""add read_at to communication_logs

Revision ID: 4ad78565299e
Revises: 5ae4df213596
Create Date: 2026-09-05 15:00:07.755433

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4ad78565299e"
down_revision = "5ae4df213596"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("communication_logs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("read_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("communication_logs", schema=None) as batch_op:
        batch_op.drop_column("read_at")

    # ### end Alembic commands ###
