"""add communications: garage settings and communication logs

Revision ID: 5ae4df213596
Revises: f4764e946226
Create Date: 2026-09-05 11:55:56.610272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae4df213596'
down_revision = 'f4764e946226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garage_communication_settings',
    sa.Column('garage_id', sa.Uuid(), nullable=False),
    sa.Column('communications_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('twilio_subaccount_sid', sa.String(length=64), nullable=True),
    sa.Column('voice_phone_number', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_sender', sa.String(length=30), nullable=True),
    sa.Column('messaging_service_sid', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['garage_id'], ['garages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garage_id', name='uq_garage_communication_settings_garage_id')
    )
    with op.batch_alter_table('garage_communication_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garage_communication_settings_garage_id'), ['garage_id'], unique=False)

    op.create_table('communication_logs',
    sa.Column('garage_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('appointment_id', sa.Uuid(), nullable=True),
    sa.Column('booking_request_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('external_provider', sa.String(length=40), server_default='twilio', nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('from_address', sa.String(length=60), nullable=True),
    sa.Column('to_address', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('trigger_event', sa.String(length=60), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('call_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['garage_id'], ['garages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communication_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communication_logs_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_communication_logs_garage_id'), ['garage_id'], unique=False)
        batch_op.create_index('ix_communication_logs_garage_id_created_at', ['garage_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communication_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_communication_logs_garage_id_created_at')
        batch_op.drop_index(batch_op.f('ix_communication_logs_garage_id'))
        batch_op.drop_index(batch_op.f('ix_communication_logs_external_id'))

    op.drop_table('communication_logs')
    with op.batch_alter_table('garage_communication_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garage_communication_settings_garage_id'))

    op.drop_table('garage_communication_settings')
    # ### end Alembic commands ###
