"""Stripe Connect account fields on garage payment settings and booking payments

Revision ID: 5ba07cf3f21d
Revises: b8e41c5a7d92
Create Date: 2026-09-16 21:43:22.459223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba07cf3f21d'
down_revision = 'b8e41c5a7d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_account_id', sa.String(length=255), nullable=True))

    with op.batch_alter_table('garage_payment_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_account_id', sa.String(length=255), nullable=True))
        # server_default so this is safe against any existing rows - the ORM
        # model itself has no server_default (new rows always pass an
        # explicit value), this is purely a backfill for rows that predate
        # this migration.
        batch_op.add_column(
            sa.Column(
                'stripe_onboarding_complete',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                'stripe_charges_enabled', sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.add_column(
            sa.Column(
                'stripe_payouts_enabled', sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.add_column(
            sa.Column(
                'stripe_details_submitted',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.create_unique_constraint(
            'uq_garage_payment_settings_stripe_account_id', ['stripe_account_id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_payment_settings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_garage_payment_settings_stripe_account_id', type_='unique')
        batch_op.drop_column('stripe_details_submitted')
        batch_op.drop_column('stripe_payouts_enabled')
        batch_op.drop_column('stripe_charges_enabled')
        batch_op.drop_column('stripe_onboarding_complete')
        batch_op.drop_column('stripe_account_id')

    with op.batch_alter_table('booking_payments', schema=None) as batch_op:
        batch_op.drop_column('provider_account_id')

    # ### end Alembic commands ###
