"""Add garage slug and booking requests

Revision ID: 5c2468d601dc
Revises: 9eed3482f4b5
Create Date: 2026-09-03 01:04:44.276689

"""
import re

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2468d601dc'
down_revision = '9eed3482f4b5'
branch_labels = None
depends_on = None


# Kept in sync with app/garages/slug.py (inlined so the migration doesn't
# depend on app code that may change or move later).
def _slugify(value):
    base = re.sub(r"^-+|-+$", "", re.sub(r"[^a-z0-9]+", "-", value.lower()))
    return (base or "garage")[:120]


def _backfill_garage_slugs(connection):
    rows = connection.execute(
        sa.text("SELECT id, name FROM garages ORDER BY created_at")
    ).fetchall()

    used = set()
    for row in rows:
        base = _slugify(row.name)
        candidate, n = base, 2
        while candidate in used:
            suffix = f"-{n}"
            candidate = f"{base[: 120 - len(suffix)]}{suffix}"
            n += 1
        used.add(candidate)
        connection.execute(
            sa.text("UPDATE garages SET slug = :slug WHERE id = :id"),
            {"slug": candidate, "id": row.id},
        )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_requests',
    sa.Column('garage_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('customer_first_name', sa.String(length=100), nullable=False),
    sa.Column('customer_last_name', sa.String(length=100), nullable=False),
    sa.Column('customer_email', sa.String(length=320), nullable=False),
    sa.Column('customer_phone', sa.String(length=40), nullable=True),
    sa.Column('vehicle_registration', sa.String(length=20), nullable=False),
    sa.Column('vehicle_make', sa.String(length=100), nullable=True),
    sa.Column('vehicle_model', sa.String(length=100), nullable=True),
    sa.Column('vehicle_year', sa.Integer(), nullable=True),
    sa.Column('vehicle_mileage', sa.Integer(), nullable=True),
    sa.Column('appointment_type_id', sa.Uuid(), nullable=True),
    sa.Column('preferred_date', sa.Date(), nullable=False),
    sa.Column('preferred_time', sa.Time(), nullable=True),
    sa.Column('preferred_employee_note', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by_employee_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('staff_notes', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('appointment_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['appointment_type_id'], ['garage_appointment_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['garage_id'], ['garages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_requests_garage_id'), ['garage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_requests_status'), ['status'], unique=False)

    # Add nullable, backfill a unique slug for every existing garage, then
    # enforce NOT NULL + the unique index.
    op.add_column('garages', sa.Column('slug', sa.String(length=120), nullable=True))
    _backfill_garage_slugs(op.get_bind())
    op.alter_column('garages', 'slug', existing_type=sa.String(length=120), nullable=False)
    op.create_index(op.f('ix_garages_slug'), 'garages', ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garages_slug'))
        batch_op.drop_column('slug')

    with op.batch_alter_table('booking_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_requests_status'))
        batch_op.drop_index(batch_op.f('ix_booking_requests_garage_id'))

    op.drop_table('booking_requests')
    # ### end Alembic commands ###
