"""add garage payment account history

Revision ID: 5f242d03154a
Revises: d9e0f1a2b3c4
Create Date: 2026-09-26 23:51:40.351764

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5f242d03154a"
down_revision = "d9e0f1a2b3c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "garage_payment_account_history",
        sa.Column("garage_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("stripe_account_id", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("detached_by_admin_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["detached_by_admin_id"], ["platform_admins.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["garage_id"], ["garages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("garage_payment_account_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_garage_payment_account_history_garage_id"), ["garage_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("garage_payment_account_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_garage_payment_account_history_garage_id"))

    op.drop_table("garage_payment_account_history")
    # ### end Alembic commands ###
