"""Complete schema: garage/user timestamps, mot records, vehicle updates

Revision ID: 603edbba4277
Revises: d658c0629b88
Create Date: 2026-08-20 14:47:54.692687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '603edbba4277'
down_revision = 'd658c0629b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mot_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('mot_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['garage_id'], ['garages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mot_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mot_records_garage_id'), ['garage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mot_records_vehicle_id'), ['vehicle_id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.create_index(batch_op.f('ix_customers_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_garage_id'), ['garage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_last_name'), ['last_name'], unique=False)
        batch_op.drop_constraint(batch_op.f('customers_garage_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'garages', ['garage_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('garages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=320), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.drop_constraint(batch_op.f('users_garage_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'garages', ['garage_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('garage_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('current_mileage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_index(batch_op.f('ix_vehicles_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_garage_id'), ['garage_id'], unique=False)
        batch_op.create_unique_constraint('uq_vehicle_garage_registration', ['garage_id', 'registration_number'])
        batch_op.drop_constraint(batch_op.f('vehicles_customer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'garages', ['garage_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('mileage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mileage', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('vehicles_garage_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('vehicles_customer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('vehicles_customer_id_fkey'), 'customers', ['customer_id'], ['id'])
        batch_op.drop_constraint('uq_vehicle_garage_registration', type_='unique')
        batch_op.drop_index(batch_op.f('ix_vehicles_garage_id'))
        batch_op.drop_index(batch_op.f('ix_vehicles_customer_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('current_mileage')
        batch_op.drop_column('garage_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_garage_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_garage_id_fkey'), 'garages', ['garage_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('garages', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('customers_garage_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('customers_garage_id_fkey'), 'garages', ['garage_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_customers_last_name'))
        batch_op.drop_index(batch_op.f('ix_customers_garage_id'))
        batch_op.drop_index(batch_op.f('ix_customers_first_name'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('mot_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mot_records_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_mot_records_garage_id'))

    op.drop_table('mot_records')
    # ### end Alembic commands ###
