"""reconcile password reset token hash index

Revision ID: 721dae0bf4a8
Revises: c544e7a7e0ed
Create Date: 2026-09-07 11:35:07.603389

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "721dae0bf4a8"
down_revision = "c544e7a7e0ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_password_reset_tokens_token_hash"), type_="unique")
        batch_op.drop_index(batch_op.f("ix_password_reset_tokens_token_hash"))
        batch_op.create_index(
            batch_op.f("ix_password_reset_tokens_token_hash"), ["token_hash"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_password_reset_tokens_token_hash"))
        batch_op.create_index(
            batch_op.f("ix_password_reset_tokens_token_hash"), ["token_hash"], unique=False
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_password_reset_tokens_token_hash"),
            ["token_hash"],
            postgresql_nulls_not_distinct=False,
        )

    # ### end Alembic commands ###
