"""booking deposits: appointment type deposit config, payment hold, booking_payments

Revision ID: 7e66710b3cf8
Revises: c2e4a8f61d93
Create Date: 2026-09-12 07:45:04.900327

Purely additive: every existing appointment type gets deposit_required=false
(server_default backfill, then the default is dropped so the ORM's own
default governs new rows - see f7066fcfe860 for the same pattern) and
deposit_currency='GBP'; every existing booking request gets a NULL
payment_hold_expires_at, meaningless for anything that already exists.
Nothing here touches existing bookings/appointments/payments (there are
none yet).
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7e66710b3cf8'
down_revision = 'c2e4a8f61d93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_webhook_events',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_payments',
    sa.Column('garage_id', sa.Uuid(), nullable=False),
    sa.Column('booking_request_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_refund_id', sa.String(length=255), nullable=True),
    sa.Column('refunded_amount_minor', sa.Integer(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_failure_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['garage_id'], ['garages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_payments_booking_request_id'), ['booking_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_payments_garage_id'), ['garage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_payments_provider_payment_id'), ['provider_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_payments_status'), ['status'], unique=False)

    op.create_table('payment_audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('garage_id', sa.Uuid(), nullable=False),
    sa.Column('booking_request_id', sa.Uuid(), nullable=True),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['garage_id'], ['garages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['booking_payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_audit_log_garage_id'), ['garage_id'], unique=False)

    with op.batch_alter_table('booking_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_hold_expires_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('garage_appointment_types', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('deposit_required', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column('deposit_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('deposit_value', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(
            sa.Column('deposit_currency', sa.String(length=3), nullable=False, server_default='GBP')
        )

    with op.batch_alter_table('garage_appointment_types', schema=None) as batch_op:
        batch_op.alter_column('deposit_required', server_default=None)
        batch_op.alter_column('deposit_currency', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_appointment_types', schema=None) as batch_op:
        batch_op.drop_column('deposit_currency')
        batch_op.drop_column('deposit_value')
        batch_op.drop_column('deposit_type')
        batch_op.drop_column('deposit_required')

    with op.batch_alter_table('booking_requests', schema=None) as batch_op:
        batch_op.drop_column('payment_hold_expires_at')

    with op.batch_alter_table('payment_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_audit_log_garage_id'))
        batch_op.drop_index(batch_op.f('ix_payment_audit_log_action'))

    op.drop_table('payment_audit_log')
    with op.batch_alter_table('booking_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_payments_status'))
        batch_op.drop_index(batch_op.f('ix_booking_payments_provider_payment_id'))
        batch_op.drop_index(batch_op.f('ix_booking_payments_garage_id'))
        batch_op.drop_index(batch_op.f('ix_booking_payments_booking_request_id'))

    op.drop_table('booking_payments')
    op.drop_table('payment_webhook_events')
    # ### end Alembic commands ###
