"""Add walk-in queue: entries, settings, reserved windows

Revision ID: 8cc5ff1cd1bf
Revises: a9b7c6d5e4f3
Create Date: 2026-09-25 23:50:01.341267

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8cc5ff1cd1bf"
down_revision = "a9b7c6d5e4f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "walkin_reserved_windows",
        sa.Column("garage_id", sa.Uuid(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("starts_at", sa.Time(), nullable=False),
        sa.Column("ends_at", sa.Time(), nullable=False),
        sa.Column("reserved_capacity", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(weekday IS NULL) <> (date IS NULL)",
            name="ck_walkin_reserved_windows_weekday_xor_date",
        ),
        sa.CheckConstraint("reserved_capacity >= 1", name="ck_walkin_reserved_windows_capacity"),
        sa.CheckConstraint("starts_at < ends_at", name="ck_walkin_reserved_windows_time_order"),
        sa.ForeignKeyConstraint(["garage_id"], ["garages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("walkin_reserved_windows", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_walkin_reserved_windows_garage_id"), ["garage_id"], unique=False
        )

    op.create_table(
        "garage_queue_settings",
        sa.Column("garage_id", sa.Uuid(), nullable=False),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("average_mode", sa.String(length=10), nullable=False),
        sa.Column("manual_average_minutes", sa.Integer(), nullable=True),
        sa.Column("no_show_timeout_minutes", sa.Integer(), nullable=True),
        sa.Column("default_appointment_type_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["default_appointment_type_id"], ["garage_appointment_types.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["garage_id"], ["garages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("garage_id", name="uq_garage_queue_settings_garage_id"),
    )
    with op.batch_alter_table("garage_queue_settings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_garage_queue_settings_garage_id"), ["garage_id"], unique=False
        )

    op.create_table(
        "queue_entries",
        sa.Column("garage_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("end_reason", sa.String(length=30), nullable=True),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("ticket_number", sa.Integer(), nullable=False),
        sa.Column("sort_key", sa.Integer(), nullable=False),
        sa.Column("customer_first_name", sa.String(length=100), nullable=False),
        sa.Column("customer_last_name", sa.String(length=100), nullable=True),
        sa.Column("customer_phone", sa.String(length=40), nullable=False),
        sa.Column("sms_opt_in", sa.Boolean(), nullable=False),
        sa.Column("vehicle_registration", sa.String(length=20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("appointment_type_id", sa.Uuid(), nullable=True),
        sa.Column("service_minutes", sa.Integer(), nullable=False),
        sa.Column("public_token_hash", sa.String(length=64), nullable=False),
        sa.Column("called_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("called_sms_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("appointment_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["appointment_id"], ["appointments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["appointment_type_id"], ["garage_appointment_types.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["garage_id"], ["garages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "garage_id", "service_date", "ticket_number", name="uq_queue_entries_garage_date_ticket"
        ),
        sa.UniqueConstraint("public_token_hash", name="uq_queue_entries_public_token_hash"),
    )
    with op.batch_alter_table("queue_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_queue_entries_appointment_id"), ["appointment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_queue_entries_appointment_type_id"),
            ["appointment_type_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_queue_entries_garage_date_status",
            ["garage_id", "service_date", "status"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_queue_entries_garage_id"), ["garage_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_queue_entries_garage_id"))
        batch_op.drop_index("ix_queue_entries_garage_date_status")
        batch_op.drop_index(batch_op.f("ix_queue_entries_appointment_type_id"))
        batch_op.drop_index(batch_op.f("ix_queue_entries_appointment_id"))

    op.drop_table("queue_entries")
    with op.batch_alter_table("garage_queue_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_garage_queue_settings_garage_id"))

    op.drop_table("garage_queue_settings")
    with op.batch_alter_table("walkin_reserved_windows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_walkin_reserved_windows_garage_id"))

    op.drop_table("walkin_reserved_windows")
    # ### end Alembic commands ###
