"""add appointment reminder settings; generalize reminder vehicle

Revision ID: a146785a0008
Revises: a31d84ce9287
Create Date: 2026-09-22 13:56:33.343174

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a146785a0008"
down_revision = "a31d84ce9287"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appointment_reminder_settings",
        sa.Column("garage_id", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("channels", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["garage_id"], ["garages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("garage_id", name="uq_appointment_reminder_settings_garage_id"),
    )
    with op.batch_alter_table("appointment_reminder_settings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_appointment_reminder_settings_garage_id"), ["garage_id"], unique=False
        )

    op.create_table(
        "appointment_reminder_timings",
        sa.Column("settings_id", sa.Uuid(), nullable=False),
        sa.Column("hours_before", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["settings_id"], ["appointment_reminder_settings.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "settings_id", "hours_before", name="uq_appointment_reminder_timing_hours"
        ),
    )
    with op.batch_alter_table("appointment_reminder_timings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_appointment_reminder_timings_settings_id"), ["settings_id"], unique=False
        )

    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.alter_column("vehicle_id", existing_type=sa.UUID(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.alter_column("vehicle_id", existing_type=sa.UUID(), nullable=False)

    with op.batch_alter_table("appointment_reminder_timings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_appointment_reminder_timings_settings_id"))

    op.drop_table("appointment_reminder_timings")
    with op.batch_alter_table("appointment_reminder_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_appointment_reminder_settings_garage_id"))

    op.drop_table("appointment_reminder_settings")
    # ### end Alembic commands ###
