"""add conversation engine: sessions, callbacks, templates, automation settings

Revision ID: c544e7a7e0ed
Revises: 4ad78565299e
Create Date: 2026-09-05 18:28:49.454420

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c544e7a7e0ed"
down_revision = "4ad78565299e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "garage_communication_automation_settings",
        sa.Column("garage_id", sa.Uuid(), nullable=False),
        sa.Column("booking_ack_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "booking_confirmation_enabled", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column("reminder_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("reminder_hours_before", sa.Integer(), server_default="24", nullable=False),
        sa.Column("missed_call_ack_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "conversation_automation_enabled", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["garage_id"], ["garages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "garage_id", name="uq_garage_communication_automation_settings_garage_id"
        ),
    )
    with op.batch_alter_table("garage_communication_automation_settings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_garage_communication_automation_settings_garage_id"),
            ["garage_id"],
            unique=False,
        )

    op.create_table(
        "garage_message_templates",
        sa.Column("garage_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["garage_id"], ["garages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("garage_id", "key", name="uq_garage_message_templates_garage_key"),
    )
    with op.batch_alter_table("garage_message_templates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_garage_message_templates_garage_id"), ["garage_id"], unique=False
        )

    op.create_table(
        "conversation_sessions",
        sa.Column("garage_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("customer_phone", sa.String(length=40), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="ACTIVE", nullable=False),
        sa.Column("intent", sa.String(length=40), nullable=True),
        sa.Column("workflow_step", sa.String(length=40), nullable=True),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("handoff_reason", sa.String(length=200), nullable=True),
        sa.Column("last_external_message_id", sa.String(length=100), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["garage_id"], ["garages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_sessions_garage_id"), ["garage_id"], unique=False
        )
        batch_op.create_index(
            "ix_conversation_sessions_lookup",
            ["garage_id", "channel", "customer_phone", "status"],
            unique=False,
        )

    op.create_table(
        "callback_requests",
        sa.Column("garage_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("phone_number", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("preferred_time", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="PENDING", nullable=False),
        sa.Column("source_session_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["garage_id"], ["garages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_session_id"], ["conversation_sessions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("callback_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_callback_requests_garage_id"), ["garage_id"], unique=False
        )

    with op.batch_alter_table("booking_requests", schema=None) as batch_op:
        batch_op.alter_column("customer_email", existing_type=sa.VARCHAR(length=320), nullable=True)

    with op.batch_alter_table("communication_logs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("intent", sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("communication_logs", schema=None) as batch_op:
        batch_op.drop_column("intent")

    with op.batch_alter_table("booking_requests", schema=None) as batch_op:
        batch_op.alter_column(
            "customer_email", existing_type=sa.VARCHAR(length=320), nullable=False
        )

    with op.batch_alter_table("callback_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_callback_requests_garage_id"))

    op.drop_table("callback_requests")
    with op.batch_alter_table("conversation_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_conversation_sessions_lookup")
        batch_op.drop_index(batch_op.f("ix_conversation_sessions_garage_id"))

    op.drop_table("conversation_sessions")
    with op.batch_alter_table("garage_message_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_garage_message_templates_garage_id"))

    op.drop_table("garage_message_templates")
    with op.batch_alter_table("garage_communication_automation_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_garage_communication_automation_settings_garage_id"))

    op.drop_table("garage_communication_automation_settings")
    # ### end Alembic commands ###
