"""Add content_type, size_bytes, original_filename to checklist_item_media

Revision ID: d6015a4b1b3f
Revises: 5c2468d601dc
Create Date: 2026-09-03 08:11:02.396913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6015a4b1b3f'
down_revision = '5c2468d601dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_item_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('size_bytes', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_item_media', schema=None) as batch_op:
        batch_op.drop_column('original_filename')
        batch_op.drop_column('size_bytes')
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###
