"""Add default duration to garage appointment types

Revision ID: de3750c5d620
Revises: f7066fcfe860
Create Date: 2026-08-31 14:24:21.357699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3750c5d620'
down_revision = 'f7066fcfe860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_appointment_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_duration_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_appointment_types', schema=None) as batch_op:
        batch_op.drop_column('default_duration_minutes')

    # ### end Alembic commands ###
