"""Add provider-agnostic existing-number integration fields

Revision ID: e0b4093d1ef6
Revises: a9b7c6d5e4f3
Create Date: 2026-09-26 00:42:36.408871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b4093d1ef6'
down_revision = 'a9b7c6d5e4f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_communication_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('integration_provider_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('integration_provider_product', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('integration_capability', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('integration_carrier_sip_uri', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('integration_carrier_ip_addresses', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('integration_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('integration_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('integration_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('integration_connection_policy_sid', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('integration_ip_acl_sid', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_communication_settings', schema=None) as batch_op:
        batch_op.drop_column('integration_ip_acl_sid')
        batch_op.drop_column('integration_connection_policy_sid')
        batch_op.drop_column('integration_error')
        batch_op.drop_column('integration_status')
        batch_op.drop_column('integration_notes')
        batch_op.drop_column('integration_carrier_ip_addresses')
        batch_op.drop_column('integration_carrier_sip_uri')
        batch_op.drop_column('integration_capability')
        batch_op.drop_column('integration_provider_product')
        batch_op.drop_column('integration_provider_name')

    # ### end Alembic commands ###
