"""add feedback table

Revision ID: e1f61b2c2949
Revises: b8e41c5a7d92
Create Date: 2026-09-16 22:33:42.392733

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e1f61b2c2949"
down_revision = "b8e41c5a7d92"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("garage_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=True),
        sa.Column("business_name", sa.String(length=200), nullable=False),
        sa.Column("user_email", sa.String(length=320), nullable=False),
        sa.Column("type", sa.String(length=20), server_default="GENERAL", nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=10), server_default="NORMAL", nullable=False),
        sa.Column("done", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["garage_id"], ["garages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_feedback_employee_id"), ["employee_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_feedback_garage_id"), ["garage_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feedback_garage_id"))
        batch_op.drop_index(batch_op.f("ix_feedback_employee_id"))

    op.drop_table("feedback")
    # ### end Alembic commands ###
