"""Add garage_appointment_statuses

Revision ID: f4e8b2783149
Revises: d6015a4b1b3f
Create Date: 2026-09-03 08:17:09.201465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e8b2783149'
down_revision = 'd6015a4b1b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garage_appointment_statuses',
    sa.Column('garage_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['garage_id'], ['garages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garage_id', 'key', name='uq_garage_appointment_statuses_garage_key')
    )
    with op.batch_alter_table('garage_appointment_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garage_appointment_statuses_garage_id'), ['garage_id'], unique=False)

    # ### end Alembic commands ###

    # Backfill the built-in status set for every existing garage. Kept in sync
    # with app/appointments/statuses/defaults.py (new garages seed the same set
    # at registration).
    op.execute(
        """
        INSERT INTO garage_appointment_statuses
            (id, garage_id, key, label, color, sort_order, is_terminal, is_system, created_at, updated_at)
        SELECT gen_random_uuid(), g.id, d.key, d.label, d.color, d.sort_order, d.is_terminal, true, now(), now()
        FROM garages g
        CROSS JOIN (VALUES
            ('REQUESTED',    'Requested',     'violet',  10, false),
            ('BOOKED',       'Booked',        'blue',    20, false),
            ('IN_PROGRESS',  'In progress',   'sky',     30, false),
            ('ACTION_NEEDED','Action needed', 'red',     40, false),
            ('COMPLETED',    'Completed',     'emerald', 50, true),
            ('CANCELLED',    'Cancelled',     'slate',   60, true),
            ('NO_SHOW',      'No-show',       'amber',   70, true)
        ) AS d(key, label, color, sort_order, is_terminal)
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_appointment_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garage_appointment_statuses_garage_id'))

    op.drop_table('garage_appointment_statuses')
    # ### end Alembic commands ###
