"""Add status to garage appointment types

Revision ID: f7066fcfe860
Revises: 67b0dd2e6f6e
Create Date: 2026-08-31 13:45:13.008895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7066fcfe860'
down_revision = '67b0dd2e6f6e'
branch_labels = None
depends_on = None


def upgrade():
    # server_default backfills any existing rows to ACTIVE (the ORM default
    # is Python-side only, so ADD COLUMN NOT NULL needs its own default here
    # for rows that already exist).
    with op.batch_alter_table('garage_appointment_types', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'status', sa.String(length=20), nullable=False, server_default='ACTIVE'
            )
        )
        batch_op.alter_column('status', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_appointment_types', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
