"""add loyalty programs, ledger, and rewards

Revision ID: fc646decf504
Revises: e0b4093d1ef6
Create Date: 2026-09-26 08:43:34.323998

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fc646decf504"
down_revision = "e0b4093d1ef6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "loyalty_programs",
        sa.Column("garage_id", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("program_type", sa.String(length=20), nullable=False),
        sa.Column("earn_per_visit", sa.Integer(), nullable=False),
        sa.Column("threshold", sa.Integer(), nullable=False),
        sa.Column("reward_type", sa.String(length=20), nullable=False),
        sa.Column("reward_value_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("qualifying_appointment_type_ids", sa.JSON(), nullable=True),
        sa.Column("min_spend_minor", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["garage_id"], ["garages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("garage_id", name="uq_loyalty_programs_garage_id"),
    )
    with op.batch_alter_table("loyalty_programs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_loyalty_programs_garage_id"), ["garage_id"], unique=False
        )

    op.create_table(
        "loyalty_ledger_entries",
        sa.Column("garage_id", sa.Uuid(), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("entry_type", sa.String(length=20), nullable=False),
        sa.Column("units", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=True),
        sa.Column("actor_employee_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["actor_employee_id"], ["employees.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["garage_id"], ["garages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["program_id"], ["loyalty_programs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "program_id",
            "source_type",
            "source_id",
            "entry_type",
            name="uq_loyalty_ledger_program_source",
        ),
    )
    with op.batch_alter_table("loyalty_ledger_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_loyalty_ledger_entries_actor_employee_id"),
            ["actor_employee_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_loyalty_ledger_entries_customer_id"), ["customer_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_loyalty_ledger_entries_garage_id"), ["garage_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_loyalty_ledger_entries_program_id"), ["program_id"], unique=False
        )
        batch_op.create_index(
            "ix_loyalty_ledger_garage_customer", ["garage_id", "customer_id"], unique=False
        )

    op.create_table(
        "loyalty_rewards",
        sa.Column("garage_id", sa.Uuid(), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("cycle_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reward_type", sa.String(length=20), nullable=False),
        sa.Column("reward_value_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("redeemed_by_employee_id", sa.Uuid(), nullable=True),
        sa.Column("redemption_ledger_entry_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["garage_id"], ["garages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["program_id"], ["loyalty_programs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["redeemed_by_employee_id"], ["employees.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["redemption_ledger_entry_id"], ["loyalty_ledger_entries.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "program_id",
            "customer_id",
            "cycle_number",
            name="uq_loyalty_rewards_program_customer_cycle",
        ),
    )
    with op.batch_alter_table("loyalty_rewards", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_loyalty_rewards_customer_id"), ["customer_id"], unique=False
        )
        batch_op.create_index(
            "ix_loyalty_rewards_garage_customer_status",
            ["garage_id", "customer_id", "status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_loyalty_rewards_garage_id"), ["garage_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_loyalty_rewards_program_id"), ["program_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("loyalty_rewards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_loyalty_rewards_program_id"))
        batch_op.drop_index(batch_op.f("ix_loyalty_rewards_garage_id"))
        batch_op.drop_index("ix_loyalty_rewards_garage_customer_status")
        batch_op.drop_index(batch_op.f("ix_loyalty_rewards_customer_id"))

    op.drop_table("loyalty_rewards")
    with op.batch_alter_table("loyalty_ledger_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_loyalty_ledger_garage_customer")
        batch_op.drop_index(batch_op.f("ix_loyalty_ledger_entries_program_id"))
        batch_op.drop_index(batch_op.f("ix_loyalty_ledger_entries_garage_id"))
        batch_op.drop_index(batch_op.f("ix_loyalty_ledger_entries_customer_id"))
        batch_op.drop_index(batch_op.f("ix_loyalty_ledger_entries_actor_employee_id"))

    op.drop_table("loyalty_ledger_entries")
    with op.batch_alter_table("loyalty_programs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_loyalty_programs_garage_id"))

    op.drop_table("loyalty_programs")
    # ### end Alembic commands ###
